function [U, weights, meta] = ...
    generateProperComplexAngularRule(r, angularCfg)
%GENERATEPROPERCOMPLEXANGULARRULE Generate complex unit directions.
%
% A proper-complex direction is generated by:
%
%   eta = gReal + 1i*gImag
%   u   = eta / norm(eta)
%
% where the 2r real normal components are generated from a scrambled
% Sobol' point set.
%
% Output:
%   U        r-by-K complex unit directions
%   weights  K-by-1 equal weights
%
% MATLAB version: R2020b

validateattributes(r, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, ...
    mfilename, 'r');

K = angularCfg.numDirections;
replicateIndex = getOption( ...
    angularCfg, 'replicateIndex', 1);

baseSeed = getOption( ...
    angularCfg, 'randomSeed', 1);

skip = getOption( ...
    angularCfg, 'sobolSkip', 1024);

leap = getOption( ...
    angularCfg, 'sobolLeap', 0);

applyScramble = getOption( ...
    angularCfg, 'scramble', true);

probabilityClip = getOption( ...
    angularCfg, 'probabilityClip', 1e-12);

validateattributes(K, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, ...
    mfilename, 'angularCfg.numDirections');

if exist('sobolset', 'file') ~= 2
    error('generateProperComplexAngularRule:SobolUnavailable', ...
        'sobolset is unavailable.');
end

scrambleSeed = ...
    baseSeed + 104729 * (replicateIndex - 1);

rng(scrambleSeed, 'twister');

pointSet = sobolset(2 * r, ...
    'Skip', skip, ...
    'Leap', leap);

if applyScramble
    pointSet = scramble( ...
        pointSet, 'MatousekAffineOwen');
end

P = net(pointSet, K);

P = min(max( ...
    P, probabilityClip), ...
    1 - probabilityClip);

Z = -sqrt(2) * erfcinv(2 * P);

Zreal = Z(:, 1:r);
Zimag = Z(:, (r + 1):(2 * r));

% The factor 1/sqrt(2) is unnecessary because every vector is normalized.
Eta = Zreal + 1i * Zimag;

norms = sqrt(sum(abs(Eta).^2, 2));

if any(~isfinite(norms)) || any(norms <= 0)
    error('generateProperComplexAngularRule:InvalidNorm', ...
        'A proper-complex direction has zero or nonfinite norm.');
end

U = bsxfun(@rdivide, Eta.', norms.');

weights = ones(K, 1) / K;

meta = struct();
meta.method = 'rqmcProperComplex';
meta.dimension = r;
meta.realSobolDimension = 2 * r;
meta.numDirections = K;
meta.replicateIndex = replicateIndex;
meta.scrambleSeed = scrambleSeed;
meta.scrambled = applyScramble;
meta.sobolSkip = skip;
meta.sobolLeap = leap;
meta.probabilityClip = probabilityClip;

end

function value = getOption(options, fieldName, defaultValue)

if isfield(options, fieldName) && ...
        ~isempty(options.(fieldName))
    value = options.(fieldName);
else
    value = defaultValue;
end

end